services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: theins
      POSTGRES_USER: theins
      POSTGRES_PASSWORD: ith4837wiuesq93r8wgfiub
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx/localhost.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
